# AnaItemy - Konfiguracja

# ==========================================
#         SYSTEM OCHRONY PRZED EVENTÓWKAMI
# ==========================================
item-protection:
  # Włącz/wyłącz globalny system ochrony
  enabled: true
  
  # Czas ochrony w sekundach (domyślnie 4s)
  duration: 4

excalibur:
  # Ilość zabójstw potrzebna do pełnego naładowania miecza
  max-kills: 100

hydroklatka:
  # Promień klatki (bloki)
  radius: 8
  
  # Czas trwania klatki (sekundy)
  duration: 10
  
  # Czas animacji budowania (ticki, 20 = 1 sekunda)
  animation-duration: 30
  
  # Cooldown między użyciami (sekundy)
  cooldown: 180
