name: AnaItemy
version: '${project.version}'
main: pl.anaheim.anaitemy.AnaItemy
api-version: '1.21'
authors: [ ]
description: Plugin dodający customowe przedmioty eventowe.
softdepend: [WorldGuard, Citizens, AnacodeAntylogout, WorldEdit]

commands:
  itemyeventowe:
    description: Otwiera GUI z itemami eventowymi.
    usage: /itemyeventowe [reload] [kills <liczba>] [give <id> <nick> <ilość>] [cooldown reset <nick>] [klatwa <naloz|zdejmij> <nick>]
    permission: anaitemy.admin
